version: "3.8"
services:
  db:
    container_name: mysql
    build: ./db
    image: bae11b/trio-task-mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-db
      volumes:
      -type: volume
      source: trio-tast-db
      target: /var/lib/mysql
  flask-app:
    container_name: flask-app
    build: ./flask-app
    image: bae11b/trio-task-flask-app

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind     
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf